### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mjay9876** [HendrikRoth/node-red-contrib-oled#26]
hallo 

when i try to install it in node red - home assistant it will not work dosent it work any more or do i do something wrong ?

Mikkel

-----------------------------------------------------------
2022-04-11T16:58:59.821Z Install : node-red-contrib-oled 0.2.1

2022-04-11T16:58:59.240Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-oled@0.2.1
2022-04-11T16:59:04.193Z [err] npm
2022-04-11T16:59:04.193Z [err]  ERR! code 1
2022-04-11T16:59:04.193Z [err] npm ERR! path /config/node-red/node_modules/i2c-bus
2022-04-11T16:59:04.196Z [err] npm 
2022-04-11T16:59:04.196Z [err] ERR!
2022-04-11T16:59:04.196Z [err]  command failed
2022-04-11T16:59:04.196Z [err] npm ERR! command sh -c node-gyp rebuild
2022-04-11T16:59:04.196Z [err] npm ERR! gyp info it worked if it ends with ok
2022-04-11T16:59:04.196Z [err] npm ERR! gyp info using node-gyp@8.3.0
2022-04-11T16:59:04.196Z [err] npm
2022-04-11T16:59:04.196Z [err]  ERR! gyp info using node@16.14.0 | linux | x64
2022-04-11T16:59:04.196Z [err] npm ERR! gyp info find Python using Python version 3.9.7 found at "/usr/bin/python3"
2022-04-11T16:59:04.197Z [err] npm ERR! gyp info spawn /usr/bin/python3
2022-04-11T16:59:04.197Z [err] npm ERR!
2022-04-11T16:59:04.197Z [err]  gyp info spawn args [
2022-04-11T16:59:04.197Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2022-04-11T16:59:04.197Z [err] npm
2022-04-11T16:59:04.197Z [err]  ERR! gyp info spawn args   'binding.gyp',
2022-04-11T16:59:04.197Z [err] npm ERR!
2022-04-11T16:59:04.197Z [err]  gyp info spawn args   '-f',
2022-04-11T16:59:04.197Z [err] npm ERR! gyp info spawn args   'make',
2022-04-11T16:59:04.197Z [err] npm 
2022-04-11T16:59:04.197Z [err] ERR! gyp info spawn args   '-I',
2022-04-11T16:59:04.197Z [err] npm ERR! gyp info spawn args   '/config/node-red/node_modules/i2c-bus/build/config.gypi',
2022-04-11T16:59:04.197Z [err] npm
2022-04-11T16:59:04.197Z [err]  ERR! gyp info spawn args   '-I',
2022-04-11T16:59:04.197Z [err] npm ERR!
2022-04-11T16:59:04.197Z [err]  gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2022-04-11T16:59:04.197Z [err] npm ERR!
2022-04-11T16:59:04.197Z [err]  gyp info spawn args   '-I',
2022-04-11T16:59:04.197Z [err] npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.14.0/include/node/common.gypi',
2022-04-11T16:59:04.197Z [err] npm 
2022-04-11T16:59:04.197Z [err] ERR! gyp info spawn args   '-Dlibrary=shared_library',
2022-04-11T16:59:04.197Z [err] npm ERR! gyp info spawn args   '-Dvisibility=default',
2022-04-11T16:59:04.197Z [err] npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.0',
2022-04-11T16:59:04.197Z [err] npm ERR!
2022-04-11T16:59:04.198Z [err]  gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2022-04-11T16:59:04.198Z [err] npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.0/<(target_arch)/node.lib',
2022-04-11T16:59:04.198Z [err] npm
2022-04-11T16:59:04.198Z [err]  ERR! gyp info spawn args   '-Dmodule_root_dir=/config/node-red/node_modules/i2c-bus',
2022-04-11T16:59:04.198Z [err] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2022-04-11T16:59:04.198Z [err] npm ERR! gyp info spawn args   '--depth=.',
2022-04-11T16:59:04.198Z [err] npm ERR!
2022-04-11T16:59:04.198Z [err]  gyp info spawn args   '--no-parallel',
2022-04-11T16:59:04.198Z [err] npm ERR! gyp info spawn args   '--generator-output',
2022-04-11T16:59:04.198Z [err] npm ERR! gyp info spawn args   'build',
2022-04-11T16:59:04.198Z [err] npm ERR!
2022-04-11T16:59:04.198Z [err]  gyp info spawn args   '-Goutput_dir=.'
2022-04-11T16:59:04.198Z [err] npm ERR! gyp info spawn args ]
2022-04-11T16:59:04.198Z [err] npm 
2022-04-11T16:59:04.198Z [err] ERR! gyp ERR! build error 
2022-04-11T16:59:04.198Z [err] npm ERR!
2022-04-11T16:59:04.198Z [err]  gyp ERR! stack Error: not found: make
2022-04-11T16:59:04.198Z [err] npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
2022-04-11T16:59:04.198Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
2022-04-11T16:59:04.198Z [err] npm ERR!
2022-04-11T16:59:04.198Z [err]  gyp ERR! stack     at new Promise (<anonymous>)
2022-04-11T16:59:04.198Z [err] npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
2022-04-11T16:59:04.198Z [err] npm 
2022-04-11T16:59:04.199Z [err] ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
2022-04-11T16:59:04.199Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2022-04-11T16:59:04.199Z [err] npm
2022-04-11T16:59:04.199Z [err]  ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
2022-04-11T16:59:04.199Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
2022-04-11T16:59:04.199Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2022-04-11T16:59:04.199Z [err] npm 
2022-04-11T16:59:04.199Z [err] ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2022-04-11T16:59:04.199Z [err] npm ERR! gyp ERR! System Linux 5.10.108
2022-04-11T16:59:04.199Z [err] npm
2022-04-11T16:59:04.199Z [err]  ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-04-11T16:59:04.199Z [err] npm ERR!
2022-04-11T16:59:04.199Z [err]  gyp ERR! cwd /config/node-red/node_modules/i2c-bus
2022-04-11T16:59:04.199Z [err] npm ERR! gyp ERR! node -v v16.14.0
2022-04-11T16:59:04.199Z [err] npm 
2022-04-11T16:59:04.199Z [err] ERR! gyp ERR! node-gyp -v v8.3.0
2022-04-11T16:59:04.199Z [err] npm ERR!
2022-04-11T16:59:04.199Z [err]  gyp ERR! not ok
2022-04-11T16:59:04.214Z [err] 
2022-04-11T16:59:04.214Z [err] npm
2022-04-11T16:59:04.214Z [err]  ERR! A complete log of this run can be found in:
2022-04-11T16:59:04.214Z [err] npm ERR!     /root/.npm/_logs/2022-04-11T16_59_04_201Z-debug.log
2022-04-11T16:59:04.222Z rc=1

**Comment by Crashdown1977** [comment]
Hello

Same problem here.
Any ideas?

**Comment by Waterbrain** [comment]
Update to the latest version 1.0.5 and make sure that the Raspberry Pi has the i2c interface enabled.

**Comment by Crashdown1977** [comment]
After I2C activation i get the following

It is node red on Home Assistant. 
Python error? 

Python-Version | 3.10.5


TNX in advance
`
-----------------------------------------------------------
2022-07-22T20:17:30.689Z Installieren : node-red-contrib-oled 1.0.5

2022-07-22T20:17:08.873Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-oled@1.0.5
2022-07-22T20:17:11.228Z [err] npm
2022-07-22T20:17:11.230Z [err]  WARN 
2022-07-22T20:17:11.230Z [err] config production Use `--omit=dev` instead.
2022-07-22T20:17:22.370Z [err] npm ERR! code 1
2022-07-22T20:17:22.370Z [err] npm ERR! path /config/node-red/node_modules/i2c-bus
2022-07-22T20:17:22.375Z [err] npm ERR! command failed
2022-07-22T20:17:22.376Z [err] npm ERR! command sh -c node-gyp rebuild
2022-07-22T20:17:22.377Z [err] npm ERR! gyp info it worked if it ends with ok
2022-07-22T20:17:22.378Z [err] npm ERR! gyp info using node-gyp@9.0.0
2022-07-22T20:17:22.378Z [err] npm ERR! gyp info using node@16.16.0 | linux | arm64
2022-07-22T20:17:22.378Z [err] npm ERR! gyp ERR! find Python 
2022-07-22T20:17:22.378Z [err] npm ERR!
2022-07-22T20:17:22.379Z [err]  gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2022-07-22T20:17:22.379Z [err] npm ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2022-07-22T20:17:22.379Z [err] npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2022-07-22T20:17:22.379Z [err] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2022-07-22T20:17:22.379Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2022-07-22T20:17:22.379Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-07-22T20:17:22.380Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2022-07-22T20:17:22.380Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2022-07-22T20:17:22.380Z [err] npm ERR! gyp ERR! find Python 
2022-07-22T20:17:22.380Z [err] npm ERR!
2022-07-22T20:17:22.380Z [err]  gyp ERR! find Python **********************************************************
2022-07-22T20:17:22.380Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2022-07-22T20:17:22.380Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-07-22T20:17:22.380Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2022-07-22T20:17:22.380Z [err] npm 
2022-07-22T20:17:22.381Z [err] ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-07-22T20:17:22.381Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-07-22T20:17:22.381Z [err] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
2022-07-22T20:17:22.381Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2022-07-22T20:17:22.381Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-07-22T20:17:22.381Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2022-07-22T20:17:22.381Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-07-22T20:17:22.381Z [err] npm 
2022-07-22T20:17:22.382Z [err] ERR! gyp ERR! find Python **********************************************************
2022-07-22T20:17:22.382Z [err] npm ERR! gyp ERR! find Python 
2022-07-22T20:17:22.382Z [err] npm ERR! gyp ERR! configure error 
2022-07-22T20:17:22.382Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2022-07-22T20:17:22.382Z [err] npm ERR!
2022-07-22T20:17:22.382Z [err]  gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2022-07-22T20:17:22.382Z [err] npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2022-07-22T20:17:22.382Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2022-07-22T20:17:22.382Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2022-07-22T20:17:22.382Z [err] npm 
2022-07-22T20:17:22.383Z [err] ERR! gyp ERR! stack     at exithandler (node:child_process:406:5)
2022-07-22T20:17:22.383Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
2022-07-22T20:17:22.383Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
2022-07-22T20:17:22.383Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-07-22T20:17:22.383Z [err] npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
2022-07-22T20:17:22.383Z [err] npm
2022-07-22T20:17:22.383Z [err]  ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-07-22T20:17:22.383Z [err] npm ERR! gyp ERR! System Linux 5.15.32-v8
2022-07-22T20:17:22.383Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-07-22T20:17:22.383Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/i2c-bus
2022-07-22T20:17:22.383Z [err] npm
2022-07-22T20:17:22.383Z [err]  ERR! gyp ERR! node -v v16.16.0
2022-07-22T20:17:22.383Z [err] npm ERR! gyp ERR! node-gyp -v v9.0.0
2022-07-22T20:17:22.383Z [err] npm ERR! gyp ERR! not ok
2022-07-22T20:17:22.394Z [err] 
2022-07-22T20:17:22.395Z [err] npm ERR! A complete log of this run can be found in:
2022-07-22T20:17:22.395Z [err] npm
2022-07-22T20:17:22.395Z [err]  ERR!     /root/.npm/_logs/2022-07-22T20_17_11_022Z-debug-0.log
2022-07-22T20:17:22.426Z rc=1`

**Comment by Waterbrain** [comment]
What is the result when executing _update-alternatives --list python_?

**Comment by Crashdown1977** [comment]
command not found... In home assistant node red runs as plugin. Does it matter?

**Comment by Waterbrain** [comment]
Have you posted the error to Home Assistant?
